### PR TITLE
Weekly Chart enhancement

### PR DESCRIPTION
**Pull request by olcariz**
Hi, I made a more optimized and parametrized code of your weekly chart.
Now you can simply modify constants at the beginning of the dataviewjs snippet in the template, and the rest of the code will behave accordingly.
I also included the single js file associated to the chart, feel free to get rid of it if useless.
I didn't put any comment, if you need some explanation feel free to reach me, and by the way thanks for sharing your piece of workflow.

I forgot to mention, but I set the path to be the current folder of the weekly note, you might need to set `DAILY_NOTES_PATH` to `""` for your current workflow.

Regards, Olivier

### CODE REVIEW

**Comment by mulfok** [comment]
wow wow wow! thank you so much for contributing! I see no problem with this (_you did my job for me_) I would have torn my hair out trying to make the code neater, I'm not familiar with JS in the slightest 
I'll merge the changes, write some notes on filling out the graph, and leave attribution to you. Thanks again!

**Review by mulfok — APPROVED** [review]

**Comment by olcariz** [comment]
No worries what you did with what you got is already very good ! Don't hesitate to reach me if it doesn't fit the way you want or something is to be fixed. My discord pseudo is `theolivestory#2402`

**Comment by oyvindsolstad** [comment]
Thanks for making this! Super useful!

I'm curious, would it be hard to change the code so that I can set the date manually and not use the DateTime.now()-function? 

I'm asking because I would love the graph to show the data for the week it is on, even if I look at it at a later time. The way it is now, it uses the current week all the time, right?

**Comment by mulfok** [comment]
Hey there! This was something I noticed after I merged the branch myself too. I changed it in my vault, but haven't reflected the changes here yet. I'm outside right now, but I'll change it when I get home!

**Comment by mulfok** [comment]
Okie dokie! New commit should be good to go for you.
Thanks for using the template!

**Comment by oyvindsolstad** [comment]
Thank you! Got it to work now! 

My next little project is to change the code so the graph shows deviation from a set standard. Let's say you measure steps per day, hours slept, weight, [PAI](https://www.ntnu.edu/cerg/personal-activity-intelligence), calories, pages read etc. All kinds of things people would like to keep track of. 

My idea is to set a desired standard. For PAI (link above), it's easy. A healthy person should have 100 PAI every day. But if I add hours slept in a table with PAI in it, the hours slept would barely show (as PAI would range from 0-175 and hours slept from 4-9 maybe). 

So the idea is to set a standard in the code: So hours slept could be 7h 30m (or rather 450 minutes, easier to calculate), weight could be set to 85 kilos, steps per day 10 000 and so on. 

You enter the values for each day, and the graph shows how far off you are. 

If you slept 6h 30m - 390 minutes, you get a score of 86 %. (390/450x100)
If you walked 12 000 steps, you get a score of 120 % (12000/10000x100)
If you weigh in at 84 kilos, you get a score of 98 % 

and so on. 

That way, you could map different things in the same graph, but the graph makes sense as all measurements are percentages away from a wanted value. 

Makes sense?

**Comment by olcariz** [comment]
> Okie dokie! New commit should be good to go for you. Thanks for using the template!

You are becoming a rockstar !

**Comment by olcariz** [comment]
> Thank you! Got it to work now!
> 
> My next little project is to change the code so the graph shows deviation from a set standard. Let's say you measure steps per day, hours slept, weight, [PAI](https://www.ntnu.edu/cerg/personal-activity-intelligence), calories, pages read etc. All kinds of things people would like to keep track of.
> 
> My idea is to set a desired standard. For PAI (link above), it's easy. A healthy person should have 100 PAI every day. But if I add hours slept in a table with PAI in it, the hours slept would barely show (as PAI would range from 0-175 and hours slept from 4-9 maybe).
> 
> So the idea is to set a standard in the code: So hours slept could be 7h 30m (or rather 450 minutes, easier to calculate), weight could be set to 85 kilos, steps per day 10 000 and so on.
> 
> You enter the values for each day, and the graph shows how far off you are.
> 
> If you slept 6h 30m - 390 minutes, you get a score of 86 %. (390/450x100) If you walked 12 000 steps, you get a score of 120 % (12000/10000x100) If you weigh in at 84 kilos, you get a score of 98 %
> 
> and so on.
> 
> That way, you could map different things in the same graph, but the graph makes sense as all measurements are percentages away from a wanted value.
> 
> Makes sense?

Okay, so you want to define an object which includes standard for all types of data, then rendering a chart which contains data deviation in percent from the standard. This should be good, I am looking for refactoring solutions to put code into separate files then I will let you know when I create a new branch for this.

**Comment by mulfok** [comment]
I'll be keeping my eyes peeled for this too haha--lord _knows_ I wouldn't be able to do it :joy:

**Comment by olcariz** [comment]
allright, I have been making changes, time for a merge with instructions folks

**Pull request merged**
